### ISSUE TITLE
"Error reading from socket"/Citra also crashing (was told to throw this onto the github issue page) (also never used an issue page before so hopefully I did this right)

### ISSUE THREAD

**Issue by CursiveTheFont** [PabloMK7/ArticBaseServer#1]
[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287598/citra_log.txt)

**Comment by QuentinWehkamp** [comment]
I'm having the exact same issue
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287636/citra_log.txt.old.txt)

**Comment by babtown** [comment]
I have the same issue, here is footage of what happened on the pc and 3ds in real time as well as the citra log

https://github.com/PabloMK7/ArticBaseServer/assets/30322271/c107c6cd-31c7-43ca-93a3-195ffcc917be

[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287666/citra_log.txt)

**Comment by DetectiveMecha** [comment]
Also having this problem, exact same error process as the video above
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287704/citra_log.txt.old.txt)

**Comment by nabekos** [comment]
same issue
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15288003/citra_log.txt.old.txt)

**Comment by Dal1ster** [comment]
[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15288279/citra_log.txt)
yeah, i managed to run tomodachi life the first time i used arctic base, but every time after it causes citra to throw and error and for it to get stuck at the 3 objects loading screen

**Comment by jinjimeow** [comment]
same issue

**Comment by fignewtonss** [comment]
same issue

**Comment by Fenixien** [comment]
Same issues as users above.

**Comment by PabloMK7** [comment]
Duplicate of https://github.com/PabloMK7/citra/issues/110
