### ISSUE TITLE
Feature Request - Integrate into Citra Game List

### ISSUE THREAD

**Issue by OmegaLvei** [PabloMK7/ArticBaseServer#13]
Would it be possible for you allow us to view what games we have installed, and run said games from the Citra homescreen? Been daily driving this feature for a while now to play my games and I love it, but it's undeniably a bit cumbersome to have to launch artic base, then launch a game. 

Would it be possible to instead launch artic base on the 3DS and then have installed games show on the client, and then be able to launch them from there? Would make things a lot more convienient for the end user.

**Comment by PabloMK7** [comment]
Hello, this is outside the scope of the tool
