### ISSUE TITLE
Does it work on old 3ds XL?

### ISSUE THREAD

**Issue by BlazeVertex** [PabloMK7/ArticBaseServer#14]
I saw on YouTube people promoting it but Does it work on the Old 3ds XL? They claimde it worked on all devices that are in the 3ds family.

**Comment by PabloMK7** [comment]
Yes, but please do not create issues for simple questions like that, instead https://tryitands.ee

**Comment by BlazeVertex** [comment]
> Yes, but please do not create issues for simple questions like that, instead https://tryitands.ee

I did it bcs it was not stated in the Read me?
