### ISSUE TITLE
Luma3DS romfs overrides are not used when broadcasting game data

### ISSUE THREAD

**Issue by NerduMiner** [PabloMK7/ArticBaseServer#15]
I have a romfs override on both hardware and emulator that translates the game 電波人間のRPG FREE!(The Denpa Men: Free!) into English, as my level of Japanese isn't sufficient to enjoy the game in its native language. However, streaming the game through Arctic Base does not recognize these overrides and thus will not send the translated game files to the emulator.

The emulator overrides not being used is understandable given the scope of this project.

**Comment by PabloMK7** [comment]
As mentioned in the Readme, mods are not supported at this moment.
