### ISSUE TITLE
Server:  Cannot create socket

### ISSUE THREAD

**Issue by whynot088** [PabloMK7/ArticBaseServer#16]
whenever i open a game with ArticBase it gives me this error

**Comment by whynot088** [comment]
> open a game with ArticBase it gives me this erro

**Comment by MargoSizemore** [comment]
same issue :(

**Comment by PabloMK7** [comment]
Get a more stable internet connection

**Comment by btl200** [comment]
Ok so i managed to get artic base working without changing anything other then the emulator never mind i’m good now
