### ISSUE TITLE
Monster Hunter XX fails to detect SD card

### ISSUE THREAD

**Issue by archenemi** [PabloMK7/ArticBaseServer#17]
I'm playing a patched version for text to be in English and the game runs normally as such, but no save data is passed to Citra.

**Comment by PabloMK7** [comment]
If no save data is passed to citra, it means the game itself has no save data. Since you are using a modded build, I can only guess you are using a .cia or something, which probably doesn't have save data.

**Comment by archenemi** [comment]
Hm. I was sure most, if not all my games were installed as .cia on my system, and I tested a few others that seemed to work just fine. I do notice that there's no save to backup on Checkpoint, but there is extdata to backup. I imagine that's related.

**Comment by gjunnila** [comment]
Adding onto this, MHXX with multiple different english patches works fine on my system and (n)3ds. Save data is detected as normal.
Cannot be reproduced on 1.0 or 1.1 of artic base server with MHXX v1.4

**Comment by archenemi** [comment]
Tried again to take a look at the log and it reads
`o=0x00000000, bs=0x00481d88, wbs=0x00480000
Worker 1: FSFILE_Read method error: 8`
Repeats the same message with Worker 0 and Worker 3.

**Comment by Fuadevil007** [comment]
![photo_6269071876450008258_y](https://github.com/PabloMK7/ArticBaseServer/assets/44535059/839ff64b-b9fc-448e-9dd0-8656ed3af87c)
