### ISSUE TITLE
Audio Stuttering on Virtual Console games

### ISSUE THREAD

**Issue by St3f4n1986** [PabloMK7/ArticBaseServer#18]
First of all, amazing tool!

I've been trying multiple games, all 3ds games i've tried are running smooth. But the virtual console games i tried (pokémon red and blue, pokemon tcg) are all experiencing massive audio stutters. Video is running smooth though.

Luma, Artic are all up to date.

**Comment by PabloMK7** [comment]
Hello, this is probably an issue in citra and not with the server itself. Please open the issue in the citra repo

**Comment by cobaltw** [comment]
I know you've already closed this but I'd like to add that this happens with every game I have tried, while running them straight from citra doesn't have this problem
