### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by OpenSauce04** [PabloMK7/ArticBaseServer#2]
I want to financially support the continuous development of this black magic piece of software that I could never have even imagined a month ago.

This software will fundamentally change how I play 3DS games forever, as it perfectly fits my use case. I want to do my part to incentivise continuous improvement into the future, and I'm sure others feel the same.

I understand if you're hesitant on this and feel the shadow of big N looming.

**Comment by PabloMK7** [comment]
Hello, thank you but I do this stuff for non-profit goals. :)
