### ISSUE TITLE
[Feature Request] Emulator-2-emulator support 

### ISSUE THREAD

**Issue by pacoa-kdbg** [PabloMK7/ArticBaseServer#27]
To avoid having to copy games + saves to one device to another, would be nice to have emulator to emulator support.

**Comment by PabloMK7** [comment]
Hello, such feature is outside the scope of the tool.

**Comment by pacoa-kdbg** [comment]
Understandable, any specifics about it ?

Do you see it to be possible even if not planned or is it something that could be implemented in a different way from the emulator itself ?
