### ISSUE TITLE
"Failed to launch Artic Base"

### ISSUE THREAD

**Issue by someguyexist** [PabloMK7/ArticBaseServer#28]
I pressed A to launch artic base on my 3ds and at the top it says "[I]Launching Artic Base [E] Unsupported plugin loader version, [E] please update Luma3DS [E] Failed to launch Artic Base" can anyone help me please?

**Comment by PabloMK7** [comment]
Please update Luma3DS: https://github.com/LumaTeam/Luma3DS/wiki/Installation-and-upgrade#Upgrading

**Comment by someguyexist** [comment]
it was actually b9strap but thanks so much!!! i just needed to update my b9s
