### ISSUE TITLE
"Couldn't set memblock size" error appearing sporadically on opening a game

### ISSUE THREAD

**Issue by JadeJuno** [PabloMK7/ArticBaseServer#29]
Sometimes, when opening a game, Luma (presumably? It has the look of a Luma message) shows an error with the following:
```
Plugin loader
	Couldn't set memblock size.
	Error code: 0xD8A077F9
```
When closing the error, the game boots as normal on the console, as if ArticBase wasn't doing anything.
For now, restarting ArticBase makes it work, so it's not a big issue, but it's still a bit weird.

If it helps, the game I've been using recently that causes this issue is The Legend of Zelda: Ocarina of Time 3D, and I'm playing on an Old2DS. If any further info is needed feel free to ask.

**Comment by PabloMK7** [comment]
Hello, I also noticed this. However it's an issue with Luma3DS, so I'm closing the issue here as it's unrelated with Artic Base.
I might look into this eventually, mind telling with which game did this happen?.

**Comment by guusangeren** [comment]
Although closed-not planned, just to let you know: happened to me on Bravely Default. My guess was it actually had something to do with game/mem sizes. It launched on my second try though.
