### ISSUE TITLE
[SUGGESTION] Add a way to toggle the bottomscreen when using the 3DS as controller

### ISSUE THREAD

**Issue by Lucipo** [PabloMK7/ArticBaseServer#30]
The blaring white screen can be a bit annoying for some, a way to just toggle it off might be nice, and then toggle it back on whenever you're done. Especially when using the 3ds as a controller functionally.

Finding a way to activate this without conflicting with a possible game's controls may be hard, not as bad if it's customizable.

**Comment by PabloMK7** [comment]
Hello, this is already implemented, enable sleep mode before connecting, or exit controller mode and enter sleep mode, then press select.
