### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Timothy14f** [PabloMK7/ArticBaseServer#31]
The connection keeps failing. Both devices are on the same network. I am using Citra (Android).
![photo](https://github.com/user-attachments/assets/9946b459-5b65-482e-86c0-b0389d890fcc)
![Screenshot_20240721_173253_Citra](https://github.com/user-attachments/assets/ef08136f-d38e-46af-9edf-5cbea155a48b)

**Comment by PabloMK7** [comment]
Update citra to the latest verison and try again.

**Comment by Timothy14f** [comment]
Still not working.

**Comment by PabloMK7** [comment]
Please send the citra log.

**Comment by Timothy14f** [comment]
[citra_log.txt.old.txt](https://github.com/user-attachments/files/16366675/citra_log.txt.old.txt)

**Comment by PabloMK7** [comment]
The log only mentions a generic communication error. There might be network issues with your console or phone.

**Comment by Timothy14f** [comment]
I have no visible network problems at all.

**Comment by Timothy14f** [comment]
So you have no plan? Me neither.

**Comment by PabloMK7** [comment]
This is caused by some misconfiguration in your network. Closing as it's not an artic base bug.
