### ISSUE TITLE
[Enhancement] Add a File Cache

### ISSUE THREAD

**Issue by MelonSpeedruns** [PabloMK7/ArticBaseServer#32]
I'm imagining a system where the first time a file is sent to Citra, it is cached akin to a shader in a file, and the second time that same file is loaded, it reads from the cache instead of sending the whole file over from the 3DS.

I'm sure this would allow for faster loading of the game the more you play it and between play sessions as well, but I wonder how you could detect if the data is the same across sendings.

**Comment by PabloMK7** [comment]
Hello, this is already implemented.
A cache persistent between sessions is outside the scope of the tool.
