### ISSUE TITLE
Sticker Star Save Corruption

### ISSUE THREAD

**Issue by AnonymousUser351** [PabloMK7/ArticBaseServer#33]
Paper Mario: Sticker Star (eough) corrupts save data in a loop on the title screen. Works for other games I've tested yet Sticker Star thinks it is too cool to be streamed (It isn't). Also dumped the ROM and the ROM works perfectly.

![IMG_0184](https://github.com/user-attachments/assets/45690138-cfa0-4b14-be45-199d6134055c)

New2DS is running on Luma3DS v13.1.2 (SYS 11.17.0-50U) and ArticBase v1.2.0

Emulator is the current latest Lime3DS build. Also happens in the latest PabloMK7/Citra build.

**Comment by PabloMK7** [comment]
The output in the server is very strange, errors related to sockets only happen if there is a network problem. Can you retry but enable the debug log by pressing X in the console?

**Comment by AnonymousUser351** [comment]
[IMG_0184.webm](https://github.com/user-attachments/assets/730b54c9-c4db-46ad-8bfd-595127aff7c9)

**Comment by PabloMK7** [comment]
Got a copy of the game and can reproduce.

**Comment by AnonymousUser351** [comment]
Yeah…. no .. not paying $10-15 for Sticker Star.

**Comment by PabloMK7** [comment]
What? I said that I got a copy of the game, and I'm able to see the issue. Anyways, if you don't own the game I cannot assist further.

**Comment by AnonymousUser351** [comment]
Oh, I read it as “Get a copy of the game and reproduce it”. The consequences of a 4 hour sleep.

**Comment by PumpkinMH** [comment]
I can confirm I also have this issue as well in Sticker Star. Using Artic Base 1.2.0, Luma 3DS 13.1.1, and PabloMK7 Citra 518f723

**Comment by Tom871530** [comment]
Hi Pablo, I am having the same issue with Sticker Star.  Has this issue been resolved?

Thank You,
Tom
