### ISSUE TITLE
REQUEST: Screen Mirroring Option for Artic Base

### ISSUE THREAD

**Issue by R2MGaming** [PabloMK7/ArticBaseServer#36]
I just tried out the new Artic Base using Lime3DS (with the Artic Base Controller option enabled, and so far I like how the 3DS and 2DS systems are able to be used as controllers for both Citra and Lime3DS. I do have one, I repeat "one request" to make for this:

https://gbatemp.net/threads/ctroll3d-control-the-citra-emulator-from-your-3ds.584275/ Since the user @CarlosEFML's 3DS is broken, would it be possible to actually have THIS work for both Citra and Lime3DS for Windows maybe?

**Comment by Reual4412** [comment]
That project I didn't know existed, which is cool to see. I was originally going to request, since I know that the 3ds is pretty limited regarding network speeds, and artic base in it's current configuration doesn't allow it to act as just purely a controller. That users could  draw on citra's bottom screen (like pausing emulation, take your mouse. draw out where the game is expecting a swipe input or whatever action) and then sending that to the 3ds.

**Comment by R2MGaming** [comment]
> That project I didn't know existed, which is cool to see. I was originally going to request something similar. Since I know that the 3ds is pretty limited regarding network speeds, and artic base in it's current configuration doesn't allow it to act as just purely a controller. That request being users could draw on citra's bottom screen (like pausing emulation, take your mouse. draw out where the game is expecting a swipe input or whatever action) and then sending that to the 3ds's bottom screen (so rather than sending the whole bottom screen, you get what you drew) as a guide. Which admittedly would be a bit clunky, but for certain games that be good enough.

I could imagine that working for WarioWare Gold using Artic Base.

**Comment by ZaneDragonBorn** [comment]
Yes this is a must have. I always found it strange that the app even featured a touch control supported bottom screen, yet didn't project what was on the PC client there. I can totally see this being difficult as streaming the game to PC probably uses enough bandwidth. But I'd be curious if its possible to somehow run it on both PC and 3DS at the same time? or maybe stream back a low quality ver of the bottom screen to the 3DS?

**Comment by PabloMK7** [comment]
Hello, all the suggestions proposed here, except for streaming back the bottom screen (which may or may not be possible), are outside the scope of the tool, sorry.
