### ISSUE TITLE
Sun and Moon launch as if Artic is not running

### ISSUE THREAD

**Issue by Fenixien** [PabloMK7/ArticBaseServer#4]
Whenever I choose Pokemon Sun/Moon or UltraSun/UltraMoon on my Old 3DSXL it does not boot into Artic. Instead it boots into the game normally. This does not impact any other game I have tested, like Alpha Sapphire.

**Comment by Andromander** [comment]
Tried this with Monster Hunter 4 Ultimate, also did not do anything. Using an Old 3DS, launched the game from cartridge, if that means anything.

**Comment by m00542** [comment]
io tried to play Pokémon black and its starts like its normal what can i do to fix this

**Comment by m00542** [comment]
and im running 1.0,1 as well

**Comment by m00542** [comment]
and i have luma v13.1.1

**Comment by PabloMK7** [comment]
> io tried to play Pokémon black and its starts like its normal what can i do to fix this

DS mode games are not supported
