### ISSUE TITLE
Shader compilation

### ISSUE THREAD

**Issue by RodrigoTR04** [PabloMK7/ArticBaseServer#43]
This not an issue, but a question.

With Arctic Base Server do shaders still need to be compiled during gameplay? If the compilation is needed is it possible to have purely a "stream mode" where the console is only streaming the screen akin to other programs that have fallen out of use like Kit Kat Slim and Snickerstream? Those programs are quite old and have a lot of dropped frames and instabilities while running.

**Comment by PabloMK7** [comment]
Hello, artic base is not screen recording, it's emulation. Therefore shader compilation still needs to happen and screen sharing not possible.
