### ISSUE TITLE
Monster Hunter 3 Ultimate averaging at 65% speed

### ISSUE THREAD

**Issue by ebarker21** [PabloMK7/ArticBaseServer#45]
As the title says, MH3U consistently runs at a lower speed when in-game. Debug menu reads 

[D] Worker (0/1/2/3): Processing FSFILE_Read (rID (number is constantly increasing at a rapid rate))
[D] Read o=(0/1/2/3)x(Increasing), l=0x00001000

No idea if this helps or not, thank you for your work!

**Comment by ebarker21** [comment]
Running on latest Lime3DS (2118)

**Comment by PabloMK7** [comment]
Hello, the emulation speed depends on the emulator itself, and not Artic Base. Please open an issue in the emulator GitHub page instead!
