### ISSUE TITLE
[Feature request] "Stream savedata only" mode, to reduce game lag

### ISSUE THREAD

**Issue by Darthagnon** [PabloMK7/ArticBaseServer#47]
I have just tested ArcticBase and it is incredible, only marred by occasional lag spikes and sound dropouts. I was afraid to raise the graphics scaling in the emulator because of this. 

Would it be possible to implement a mode that streams only the savedata and extdata from the console? [Similar to this feature request I made in Lime3DS #491](https://github.com/Lime3DS/Lime3DS/issues/491), though I'm not sure if this would be better implemented on the emulator side or the ArcticBaseServer side. 

For example, for my own 2DS, I have my games dumped and backed up on my PC, and can load them directly from the emulator - it would be nice if the emulator, when streaming via ArcticBase, could detect that the gameID it's streaming exists as a local backup, and load  it directly from the PC, rather than streamed slowly from the 2DS, while still saving game progress and loading extdata DLC from the 3DS. This would eliminate lag and improve loading times by a lot, at the cost of using a bit of harddrive space to backup the games already present on the 3DS (which most people probably do anyway).

**Comment by PabloMK7** [comment]
Hello, lag spikes and sound dropouts are unrelated to Artic Base, the only thing you will experience is longer load times.
In any case, what you are asking is outside the scope of the tool sorry.
