### ISSUE TITLE
Can't open a save file from Story Of Seasons Trio Of Town due to DLC download requirement.

### ISSUE THREAD

**Issue by dsiver144** [PabloMK7/ArticBaseServer#5]
As the title, I couldn't open my save file from this game. Does this support DLC?
![image](https://github.com/PabloMK7/ArticBaseServer/assets/15687760/a456da3f-f987-4d38-b7cd-11982aefc343)
I even tried redownload the DLC from Start menu but it just didn't work.

**Comment by PabloMK7** [comment]
From the [README](README.md) DLC support is not added yet.

**Comment by dsiver144** [comment]
Thank you!
