### ISSUE TITLE
Fatal Error - Fire Emblem Fates

### ISSUE THREAD

**Issue by SnakeManvsArbok** [PabloMK7/ArticBaseServer#7]
Hello there! I've attempted using ArticBase with both the newest version of Lime3DS, and with the dev's most recent Citra modification. Both logs have been included.
[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15300762/citra_log.txt)
[lime3ds_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15300763/lime3ds_log.txt)

**Comment by PabloMK7** [comment]
Duplicate of #6
