### ISSUE TITLE
Feat: Allow spoofing host console settings

### ISSUE THREAD

**Issue by OpenSauce04** [PabloMK7/ArticBaseServer#8]
I am proposing a feature where the games being run on the emulator with imitate the current system configuration of the host 3DS.

This would be useful for games such as Tomodachi Life, which has an anticheat system built-in which disables all shop rotations for 24 hours after a change in console ID.
This obviously makes playing the game through Artic Base not particularly appealing, as each time you swap between the emulator and the real 3DS, the anticheat system will be activated, hypothetically leading to shops never changing rotation if you swap devices frequently.

This could either be the default behavior or an opt-in setting depending on your preference.

I am unsure if this is covered under this sentence in the readme:
> Things that will never be implemented
> ...
> - Dump any kind of system data, such as keys, archives or console unique files. This includes caching data between play sessions.

**Comment by PabloMK7** [comment]
Which console ID are you talking about?

**Comment by OpenSauce04** [comment]
I believe it checks this value. The in-game message in Tomodachi Life specifically mentions the game being played on a different console, and I'm not sure how else the game could be discerning that
![image](https://github.com/PabloMK7/ArticBaseServer/assets/48618519/317a9711-ac01-4c48-8305-7e3dff87b246)

**Comment by OpenSauce04** [comment]
Sorry, I was busier than expected today

I will come back to this tomorrow

**Comment by Dal1ster** [comment]
how did you even manage to get tomodachi life to run in arctic, every time i try to load it on mine, it just throws an error and gets stuck at the 3 foods loading screen

**Comment by OpenSauce04** [comment]
I have confirmed that changing only the console ID and nothing else causes this message to appear when next loading the save, indicating that the anti-cheat has been tripped:
![image](https://github.com/PabloMK7/ArticBaseServer/assets/48618519/0bbd17cd-fc24-474c-b9cc-b19661d93dfa)

> how did you even manage to get tomodachi life to run in arctic

Works absolutely fine for me ¯\\\_(ツ)_/¯

**Comment by Dal1ster** [comment]
Odd, for me on default CITRA settings when it's loading the game it just throws a critical check the log error and gets stuck, and this error doesn't happen on any of the other games I've tried with it, I'm just lost

**Comment by Dal1ster** [comment]
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15367079/citra_log.txt.old.txt)
yeah, heres a log of me attempting to boot it, and the error doesent happen on any other game that i tried (which were concentration training, pikmin movies, mario 3d land, and pokemon ultra moon)

**Comment by OpenSauce04** [comment]
TBH for the purposes of game compatibility you could probably just spoof the console ID and nothing else if that's more to your preference

**Comment by OpenSauce04** [comment]
@PabloMK7 Upon attempting to load into Tamadochi Life after installing the new version of Artic Base, I am now met with this message:

![image](https://github.com/PabloMK7/ArticBaseServer/assets/48618519/b78d016d-4ef4-4a7a-a37f-50044758f947)

After saving in the emulator and loading up on my 3DS, the same message appears there, so it seems that some check that game is doing is somehow giving different results between the emulator and the 3DS.

I have ensured that this was not caused by accidentally going back in time by a few seconds by waiting at least 5 minutes between saving on one device and loading on another.

**Comment by PabloMK7** [comment]
This makes sense, the RTC is most likely different between console and citra. Not sure if there is a way to fix this.
