### ISSUE TITLE
Firte Emblem Awakening Fatal Error

### ISSUE THREAD

**Issue by NintenZak** [PabloMK7/ArticBaseServer#9]
Hi, so when I try to launch Fire Emblem Awakening with Artic Base it does a Fatal Error, and a friend of mine say that he try pretty much all Fire Emblem games and they all do Fatal Error for some reason.
[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15326093/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15326095/citra_log.txt.old.txt)

**Comment by PabloMK7** [comment]
Duplicate of #6
